/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * 登录验证码信息
 */
@Schema(description = "登录验证码信息")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class Auth1GetnewReqVcodeinfo {
  @SerializedName("uuid")
  private String uuid = null;

  @SerializedName("vcode")
  private String vcode = null;

  @SerializedName("ismodify")
  private Boolean ismodify = null;

  public Auth1GetnewReqVcodeinfo uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * 验证码唯一标识
   * @return uuid
  **/
  @Schema(description = "验证码唯一标识")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public Auth1GetnewReqVcodeinfo vcode(String vcode) {
    this.vcode = vcode;
    return this;
  }

   /**
   * 验证码字符串
   * @return vcode
  **/
  @Schema(description = "验证码字符串")
  public String getVcode() {
    return vcode;
  }

  public void setVcode(String vcode) {
    this.vcode = vcode;
  }

  public Auth1GetnewReqVcodeinfo ismodify(Boolean ismodify) {
    this.ismodify = ismodify;
    return this;
  }

   /**
   * 修改密码界面标识符
   * @return ismodify
  **/
  @Schema(description = "修改密码界面标识符")
  public Boolean isIsmodify() {
    return ismodify;
  }

  public void setIsmodify(Boolean ismodify) {
    this.ismodify = ismodify;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Auth1GetnewReqVcodeinfo auth1GetnewReqVcodeinfo = (Auth1GetnewReqVcodeinfo) o;
    return Objects.equals(this.uuid, auth1GetnewReqVcodeinfo.uuid) &&
        Objects.equals(this.vcode, auth1GetnewReqVcodeinfo.vcode) &&
        Objects.equals(this.ismodify, auth1GetnewReqVcodeinfo.ismodify);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, vcode, ismodify);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Auth1GetnewReqVcodeinfo {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    vcode: ").append(toIndentedString(vcode)).append("\n");
    sb.append("    ismodify: ").append(toIndentedString(ismodify)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
