/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AutolockRefreshResLockinfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class AutolockRefreshResLockinfo {
  @SerializedName("docid")
  private String docid = null;

  @SerializedName("state")
  private Long state = null;

  @SerializedName("errmsg")
  private String errmsg = null;

  public AutolockRefreshResLockinfo docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * 文件id
   * @return docid
  **/
  @Schema(required = true, description = "文件id")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }

  public AutolockRefreshResLockinfo state(Long state) {
    this.state = state;
    return this;
  }

   /**
   * state等于0时表示刷新成功  state等于1表示发生异常
   * @return state
  **/
  @Schema(required = true, description = "state等于0时表示刷新成功  state等于1表示发生异常")
  public Long getState() {
    return state;
  }

  public void setState(Long state) {
    this.state = state;
  }

  public AutolockRefreshResLockinfo errmsg(String errmsg) {
    this.errmsg = errmsg;
    return this;
  }

   /**
   * 异常内容，state等于1时会填充该字段
   * @return errmsg
  **/
  @Schema(description = "异常内容，state等于1时会填充该字段")
  public String getErrmsg() {
    return errmsg;
  }

  public void setErrmsg(String errmsg) {
    this.errmsg = errmsg;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutolockRefreshResLockinfo autolockRefreshResLockinfo = (AutolockRefreshResLockinfo) o;
    return Objects.equals(this.docid, autolockRefreshResLockinfo.docid) &&
        Objects.equals(this.state, autolockRefreshResLockinfo.state) &&
        Objects.equals(this.errmsg, autolockRefreshResLockinfo.errmsg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docid, state, errmsg);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutolockRefreshResLockinfo {\n");
    
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    errmsg: ").append(toIndentedString(errmsg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
