/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AutolockTrylockReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class AutolockTrylockReq {
  @SerializedName("docid")
  private String docid = null;

  @SerializedName("force")
  private Boolean force = null;

  @SerializedName("expiretime")
  private Long expiretime = null;

  public AutolockTrylockReq docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * 文件id
   * @return docid
  **/
  @Schema(required = true, description = "文件id")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }

  public AutolockTrylockReq force(Boolean force) {
    this.force = force;
    return this;
  }

   /**
   * 是否强制获取锁，默认为false  false：不强制获取锁  true：强制获取锁
   * @return force
  **/
  @Schema(description = "是否强制获取锁，默认为false  false：不强制获取锁  true：强制获取锁")
  public Boolean isForce() {
    return force;
  }

  public void setForce(Boolean force) {
    this.force = force;
  }

  public AutolockTrylockReq expiretime(Long expiretime) {
    this.expiretime = expiretime;
    return this;
  }

   /**
   * 文件锁有效期限，默认为使用服务器可配置的超期间隔进行定期清理  -1：永久有效
   * @return expiretime
  **/
  @Schema(description = "文件锁有效期限，默认为使用服务器可配置的超期间隔进行定期清理  -1：永久有效")
  public Long getExpiretime() {
    return expiretime;
  }

  public void setExpiretime(Long expiretime) {
    this.expiretime = expiretime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutolockTrylockReq autolockTrylockReq = (AutolockTrylockReq) o;
    return Objects.equals(this.docid, autolockTrylockReq.docid) &&
        Objects.equals(this.force, autolockTrylockReq.force) &&
        Objects.equals(this.expiretime, autolockTrylockReq.expiretime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docid, force, expiretime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutolockTrylockReq {\n");
    
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("    force: ").append(toIndentedString(force)).append("\n");
    sb.append("    expiretime: ").append(toIndentedString(expiretime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
