/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AutolockTrylockRes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class AutolockTrylockRes {
  @SerializedName("issucceed")
  private Boolean issucceed = null;

  @SerializedName("lockerid")
  private String lockerid = null;

  @SerializedName("lockeraccount")
  private String lockeraccount = null;

  @SerializedName("lockername")
  private String lockername = null;

  public AutolockTrylockRes issucceed(Boolean issucceed) {
    this.issucceed = issucceed;
    return this;
  }

   /**
   * 锁定文件成功则返回true，文件已被其他用户锁定则返回false
   * @return issucceed
  **/
  @Schema(required = true, description = "锁定文件成功则返回true，文件已被其他用户锁定则返回false")
  public Boolean isIssucceed() {
    return issucceed;
  }

  public void setIssucceed(Boolean issucceed) {
    this.issucceed = issucceed;
  }

  public AutolockTrylockRes lockerid(String lockerid) {
    this.lockerid = lockerid;
    return this;
  }

   /**
   * 文件已被其他用户时，锁定者的用户id
   * @return lockerid
  **/
  @Schema(description = "文件已被其他用户时，锁定者的用户id")
  public String getLockerid() {
    return lockerid;
  }

  public void setLockerid(String lockerid) {
    this.lockerid = lockerid;
  }

  public AutolockTrylockRes lockeraccount(String lockeraccount) {
    this.lockeraccount = lockeraccount;
    return this;
  }

   /**
   * 文件已被其他用户时，锁定者用户名
   * @return lockeraccount
  **/
  @Schema(description = "文件已被其他用户时，锁定者用户名")
  public String getLockeraccount() {
    return lockeraccount;
  }

  public void setLockeraccount(String lockeraccount) {
    this.lockeraccount = lockeraccount;
  }

  public AutolockTrylockRes lockername(String lockername) {
    this.lockername = lockername;
    return this;
  }

   /**
   * 文件已被其他用户时，锁定者显示名
   * @return lockername
  **/
  @Schema(description = "文件已被其他用户时，锁定者显示名")
  public String getLockername() {
    return lockername;
  }

  public void setLockername(String lockername) {
    this.lockername = lockername;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutolockTrylockRes autolockTrylockRes = (AutolockTrylockRes) o;
    return Objects.equals(this.issucceed, autolockTrylockRes.issucceed) &&
        Objects.equals(this.lockerid, autolockTrylockRes.lockerid) &&
        Objects.equals(this.lockeraccount, autolockTrylockRes.lockeraccount) &&
        Objects.equals(this.lockername, autolockTrylockRes.lockername);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issucceed, lockerid, lockeraccount, lockername);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutolockTrylockRes {\n");
    
    sb.append("    issucceed: ").append(toIndentedString(issucceed)).append("\n");
    sb.append("    lockerid: ").append(toIndentedString(lockerid)).append("\n");
    sb.append("    lockeraccount: ").append(toIndentedString(lockeraccount)).append("\n");
    sb.append("    lockername: ").append(toIndentedString(lockername)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
