/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AutolockGetlockedfileinfosResDocinfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class AutolockGetlockedfileinfosResDocinfo {
  @SerializedName("locktime")
  private Long locktime = null;

  @SerializedName("docid")
  private String docid = null;

  @SerializedName("lockeraccount")
  private String lockeraccount = null;

  @SerializedName("lockerid")
  private String lockerid = null;

  @SerializedName("lockername")
  private String lockername = null;

  @SerializedName("path")
  private String path = null;

  public AutolockGetlockedfileinfosResDocinfo locktime(Long locktime) {
    this.locktime = locktime;
    return this;
  }

   /**
   * 文件锁创建时间（微秒时间戳）
   * @return locktime
  **/
  @Schema(required = true, description = "文件锁创建时间（微秒时间戳）")
  public Long getLocktime() {
    return locktime;
  }

  public void setLocktime(Long locktime) {
    this.locktime = locktime;
  }

  public AutolockGetlockedfileinfosResDocinfo docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * 文件id
   * @return docid
  **/
  @Schema(required = true, description = "文件id")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }

  public AutolockGetlockedfileinfosResDocinfo lockeraccount(String lockeraccount) {
    this.lockeraccount = lockeraccount;
    return this;
  }

   /**
   * 锁定者用户名
   * @return lockeraccount
  **/
  @Schema(required = true, description = "锁定者用户名")
  public String getLockeraccount() {
    return lockeraccount;
  }

  public void setLockeraccount(String lockeraccount) {
    this.lockeraccount = lockeraccount;
  }

  public AutolockGetlockedfileinfosResDocinfo lockerid(String lockerid) {
    this.lockerid = lockerid;
    return this;
  }

   /**
   * 锁定者id
   * @return lockerid
  **/
  @Schema(required = true, description = "锁定者id")
  public String getLockerid() {
    return lockerid;
  }

  public void setLockerid(String lockerid) {
    this.lockerid = lockerid;
  }

  public AutolockGetlockedfileinfosResDocinfo lockername(String lockername) {
    this.lockername = lockername;
    return this;
  }

   /**
   * 锁定者显示名
   * @return lockername
  **/
  @Schema(required = true, description = "锁定者显示名")
  public String getLockername() {
    return lockername;
  }

  public void setLockername(String lockername) {
    this.lockername = lockername;
  }

  public AutolockGetlockedfileinfosResDocinfo path(String path) {
    this.path = path;
    return this;
  }

   /**
   * 文件路径
   * @return path
  **/
  @Schema(required = true, description = "文件路径")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutolockGetlockedfileinfosResDocinfo autolockGetlockedfileinfosResDocinfo = (AutolockGetlockedfileinfosResDocinfo) o;
    return Objects.equals(this.locktime, autolockGetlockedfileinfosResDocinfo.locktime) &&
        Objects.equals(this.docid, autolockGetlockedfileinfosResDocinfo.docid) &&
        Objects.equals(this.lockeraccount, autolockGetlockedfileinfosResDocinfo.lockeraccount) &&
        Objects.equals(this.lockerid, autolockGetlockedfileinfosResDocinfo.lockerid) &&
        Objects.equals(this.lockername, autolockGetlockedfileinfosResDocinfo.lockername) &&
        Objects.equals(this.path, autolockGetlockedfileinfosResDocinfo.path);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locktime, docid, lockeraccount, lockerid, lockername, path);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutolockGetlockedfileinfosResDocinfo {\n");
    
    sb.append("    locktime: ").append(toIndentedString(locktime)).append("\n");
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("    lockeraccount: ").append(toIndentedString(lockeraccount)).append("\n");
    sb.append("    lockerid: ").append(toIndentedString(lockerid)).append("\n");
    sb.append("    lockername: ").append(toIndentedString(lockername)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
