/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ContactorSearchResUserinfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class ContactorSearchResUserinfo {
  @SerializedName("userid")
  private String userid = null;

  @SerializedName("account")
  private String account = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("mail")
  private String mail = null;

  @SerializedName("csflevel")
  private Long csflevel = null;

  @SerializedName("groupid")
  private String groupid = null;

  @SerializedName("groupname")
  private String groupname = null;

  public ContactorSearchResUserinfo userid(String userid) {
    this.userid = userid;
    return this;
  }

   /**
   * 用户唯一标识
   * @return userid
  **/
  @Schema(required = true, description = "用户唯一标识")
  public String getUserid() {
    return userid;
  }

  public void setUserid(String userid) {
    this.userid = userid;
  }

  public ContactorSearchResUserinfo account(String account) {
    this.account = account;
    return this;
  }

   /**
   * 用户登录账号
   * @return account
  **/
  @Schema(required = true, description = "用户登录账号")
  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public ContactorSearchResUserinfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 用户显示名
   * @return name
  **/
  @Schema(required = true, description = "用户显示名")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ContactorSearchResUserinfo mail(String mail) {
    this.mail = mail;
    return this;
  }

   /**
   * 用户邮箱地址
   * @return mail
  **/
  @Schema(required = true, description = "用户邮箱地址")
  public String getMail() {
    return mail;
  }

  public void setMail(String mail) {
    this.mail = mail;
  }

  public ContactorSearchResUserinfo csflevel(Long csflevel) {
    this.csflevel = csflevel;
    return this;
  }

   /**
   * 用户密级，5~15
   * @return csflevel
  **/
  @Schema(required = true, description = "用户密级，5~15")
  public Long getCsflevel() {
    return csflevel;
  }

  public void setCsflevel(Long csflevel) {
    this.csflevel = csflevel;
  }

  public ContactorSearchResUserinfo groupid(String groupid) {
    this.groupid = groupid;
    return this;
  }

   /**
   * 用户直属联系人组id
   * @return groupid
  **/
  @Schema(required = true, description = "用户直属联系人组id")
  public String getGroupid() {
    return groupid;
  }

  public void setGroupid(String groupid) {
    this.groupid = groupid;
  }

  public ContactorSearchResUserinfo groupname(String groupname) {
    this.groupname = groupname;
    return this;
  }

   /**
   * 用户直属联系人组名称
   * @return groupname
  **/
  @Schema(required = true, description = "用户直属联系人组名称")
  public String getGroupname() {
    return groupname;
  }

  public void setGroupname(String groupname) {
    this.groupname = groupname;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactorSearchResUserinfo contactorSearchResUserinfo = (ContactorSearchResUserinfo) o;
    return Objects.equals(this.userid, contactorSearchResUserinfo.userid) &&
        Objects.equals(this.account, contactorSearchResUserinfo.account) &&
        Objects.equals(this.name, contactorSearchResUserinfo.name) &&
        Objects.equals(this.mail, contactorSearchResUserinfo.mail) &&
        Objects.equals(this.csflevel, contactorSearchResUserinfo.csflevel) &&
        Objects.equals(this.groupid, contactorSearchResUserinfo.groupid) &&
        Objects.equals(this.groupname, contactorSearchResUserinfo.groupname);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userid, account, name, mail, csflevel, groupid, groupname);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactorSearchResUserinfo {\n");
    
    sb.append("    userid: ").append(toIndentedString(userid)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mail: ").append(toIndentedString(mail)).append("\n");
    sb.append("    csflevel: ").append(toIndentedString(csflevel)).append("\n");
    sb.append("    groupid: ").append(toIndentedString(groupid)).append("\n");
    sb.append("    groupname: ").append(toIndentedString(groupname)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
