/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * FileOsuploadpartRes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class FileOsuploadpartRes {
  @SerializedName("authrequests")
  private Map<String, List<String>> authrequests = new HashMap<String, List<String>>();

  public FileOsuploadpartRes authrequests(Map<String, List<String>> authrequests) {
    this.authrequests = authrequests;
    return this;
  }

  public FileOsuploadpartRes putAuthrequestsItem(String key, List<String> authrequestsItem) {
    this.authrequests.put(key, authrequestsItem);
    return this;
  }

   /**
   * 分块上传信息map，键为数据块号，值为上传信息authrequest - authrequest[0]：请求方法 - authrequest[1]: 待上传的资源URL - authrequest[2]及以后项：请求头，格式为“key: value”
   * @return authrequests
  **/
  @Schema(required = true, description = "分块上传信息map，键为数据块号，值为上传信息authrequest - authrequest[0]：请求方法 - authrequest[1]: 待上传的资源URL - authrequest[2]及以后项：请求头，格式为“key: value”")
  public Map<String, List<String>> getAuthrequests() {
    return authrequests;
  }

  public void setAuthrequests(Map<String, List<String>> authrequests) {
    this.authrequests = authrequests;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileOsuploadpartRes fileOsuploadpartRes = (FileOsuploadpartRes) o;
    return Objects.equals(this.authrequests, fileOsuploadpartRes.authrequests);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authrequests);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileOsuploadpartRes {\n");
    
    sb.append("    authrequests: ").append(toIndentedString(authrequests)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
