/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * FileOsuploadrefreshRes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class FileOsuploadrefreshRes {
  @SerializedName("uploadid")
  private String uploadid = null;

  @SerializedName("authrequest")
  private List<String> authrequest = null;

  public FileOsuploadrefreshRes uploadid(String uploadid) {
    this.uploadid = uploadid;
    return this;
  }

   /**
   * 标识本次Multipart Upload事件
   * @return uploadid
  **/
  @Schema(description = "标识本次Multipart Upload事件")
  public String getUploadid() {
    return uploadid;
  }

  public void setUploadid(String uploadid) {
    this.uploadid = uploadid;
  }

  public FileOsuploadrefreshRes authrequest(List<String> authrequest) {
    this.authrequest = authrequest;
    return this;
  }

  public FileOsuploadrefreshRes addAuthrequestItem(String authrequestItem) {
    if (this.authrequest == null) {
      this.authrequest = new ArrayList<String>();
    }
    this.authrequest.add(authrequestItem);
    return this;
  }

   /**
   * - authrequest[0]：请求方法  - authrequest[1]: 待上传的资源URL  - authrequest[2]及以后项：请求头；若请求时reqmethod的值为“POST”，则为POST表单域的项，格式为“key: value”
   * @return authrequest
  **/
  @Schema(description = "- authrequest[0]：请求方法  - authrequest[1]: 待上传的资源URL  - authrequest[2]及以后项：请求头；若请求时reqmethod的值为“POST”，则为POST表单域的项，格式为“key: value”")
  public List<String> getAuthrequest() {
    return authrequest;
  }

  public void setAuthrequest(List<String> authrequest) {
    this.authrequest = authrequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileOsuploadrefreshRes fileOsuploadrefreshRes = (FileOsuploadrefreshRes) o;
    return Objects.equals(this.uploadid, fileOsuploadrefreshRes.uploadid) &&
        Objects.equals(this.authrequest, fileOsuploadrefreshRes.authrequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uploadid, authrequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileOsuploadrefreshRes {\n");
    
    sb.append("    uploadid: ").append(toIndentedString(uploadid)).append("\n");
    sb.append("    authrequest: ").append(toIndentedString(authrequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
