/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FileMoveReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class FileMoveReq {
  @SerializedName("docid")
  private String docid = null;

  @SerializedName("destparent")
  private String destparent = null;

  @SerializedName("ondup")
  private Long ondup = null;

  public FileMoveReq docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * 要移动的文件gns路径
   * @return docid
  **/
  @Schema(required = true, description = "要移动的文件gns路径")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }

  public FileMoveReq destparent(String destparent) {
    this.destparent = destparent;
    return this;
  }

   /**
   * 目标父对象的gns路径
   * @return destparent
  **/
  @Schema(required = true, description = "目标父对象的gns路径")
  public String getDestparent() {
    return destparent;
  }

  public void setDestparent(String destparent) {
    this.destparent = destparent;
  }

  public FileMoveReq ondup(Long ondup) {
    this.ondup = ondup;
    return this;
  }

   /**
   * - 1:检查是否重命名，重名则抛异常  - 2:默认值，如果重名冲突，自动重名  - 3:如果重名冲突，自动覆盖  
   * @return ondup
  **/
  @Schema(description = "- 1:检查是否重命名，重名则抛异常  - 2:默认值，如果重名冲突，自动重名  - 3:如果重名冲突，自动覆盖  ")
  public Long getOndup() {
    return ondup;
  }

  public void setOndup(Long ondup) {
    this.ondup = ondup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileMoveReq fileMoveReq = (FileMoveReq) o;
    return Objects.equals(this.docid, fileMoveReq.docid) &&
        Objects.equals(this.destparent, fileMoveReq.destparent) &&
        Objects.equals(this.ondup, fileMoveReq.ondup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docid, destparent, ondup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileMoveReq {\n");
    
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("    destparent: ").append(toIndentedString(destparent)).append("\n");
    sb.append("    ondup: ").append(toIndentedString(ondup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
