/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * FileGetappmetadataResItem
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class FileGetappmetadataResItem {
  @SerializedName("appid")
  private String appid = null;

  @SerializedName("appname")
  private String appname = null;

  @SerializedName("appmetadata")
  private Map<String, String> appmetadata = new HashMap<String, String>();

  public FileGetappmetadataResItem appid(String appid) {
    this.appid = appid;
    return this;
  }

   /**
   * 应用 id
   * @return appid
  **/
  @Schema(required = true, description = "应用 id")
  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public FileGetappmetadataResItem appname(String appname) {
    this.appname = appname;
    return this;
  }

   /**
   * 应用名
   * @return appname
  **/
  @Schema(required = true, description = "应用名")
  public String getAppname() {
    return appname;
  }

  public void setAppname(String appname) {
    this.appname = appname;
  }

  public FileGetappmetadataResItem appmetadata(Map<String, String> appmetadata) {
    this.appmetadata = appmetadata;
    return this;
  }

  public FileGetappmetadataResItem putAppmetadataItem(String key, String appmetadataItem) {
    this.appmetadata.put(key, appmetadataItem);
    return this;
  }

   /**
   * json 格式的应用元数据集合，key-value string 的形式
   * @return appmetadata
  **/
  @Schema(required = true, description = "json 格式的应用元数据集合，key-value string 的形式")
  public Map<String, String> getAppmetadata() {
    return appmetadata;
  }

  public void setAppmetadata(Map<String, String> appmetadata) {
    this.appmetadata = appmetadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileGetappmetadataResItem fileGetappmetadataResItem = (FileGetappmetadataResItem) o;
    return Objects.equals(this.appid, fileGetappmetadataResItem.appid) &&
        Objects.equals(this.appname, fileGetappmetadataResItem.appname) &&
        Objects.equals(this.appmetadata, fileGetappmetadataResItem.appmetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appid, appname, appmetadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileGetappmetadataResItem {\n");
    
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    appname: ").append(toIndentedString(appname)).append("\n");
    sb.append("    appmetadata: ").append(toIndentedString(appmetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
