/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FileSetfilecustomattributeReqAttribute
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class FileSetfilecustomattributeReqAttribute {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("value")
  private Object value = null;

  public FileSetfilecustomattributeReqAttribute id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * 属性ID
   * @return id
  **/
  @Schema(required = true, description = "属性ID")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public FileSetfilecustomattributeReqAttribute value(Object value) {
    this.value = value;
    return this;
  }

   /**
   * 属性值string/int/int array    type等于3时value类型为string，0为int array, 其余均为int    注： 时长单位为秒  
   * @return value
  **/
  @Schema(description = "属性值string/int/int array    type等于3时value类型为string，0为int array, 其余均为int    注： 时长单位为秒  ")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileSetfilecustomattributeReqAttribute fileSetfilecustomattributeReqAttribute = (FileSetfilecustomattributeReqAttribute) o;
    return Objects.equals(this.id, fileSetfilecustomattributeReqAttribute.id) &&
        Objects.equals(this.value, fileSetfilecustomattributeReqAttribute.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileSetfilecustomattributeReqAttribute {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
