/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FileOsinitmultiuploadRes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class FileOsinitmultiuploadRes {
  @SerializedName("docid")
  private String docid = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("rev")
  private String rev = null;

  @SerializedName("uploadid")
  private String uploadid = null;

  public FileOsinitmultiuploadRes docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * 文件的gns路径
   * @return docid
  **/
  @Schema(required = true, description = "文件的gns路径")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }

  public FileOsinitmultiuploadRes name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 文件名称，UTF8编码，创建版本时返回
   * @return name
  **/
  @Schema(required = true, description = "文件名称，UTF8编码，创建版本时返回")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FileOsinitmultiuploadRes rev(String rev) {
    this.rev = rev;
    return this;
  }

   /**
   * 文件版本号
   * @return rev
  **/
  @Schema(required = true, description = "文件版本号")
  public String getRev() {
    return rev;
  }

  public void setRev(String rev) {
    this.rev = rev;
  }

  public FileOsinitmultiuploadRes uploadid(String uploadid) {
    this.uploadid = uploadid;
    return this;
  }

   /**
   * 标识本次Multipart Upload事件
   * @return uploadid
  **/
  @Schema(required = true, description = "标识本次Multipart Upload事件")
  public String getUploadid() {
    return uploadid;
  }

  public void setUploadid(String uploadid) {
    this.uploadid = uploadid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileOsinitmultiuploadRes fileOsinitmultiuploadRes = (FileOsinitmultiuploadRes) o;
    return Objects.equals(this.docid, fileOsinitmultiuploadRes.docid) &&
        Objects.equals(this.name, fileOsinitmultiuploadRes.name) &&
        Objects.equals(this.rev, fileOsinitmultiuploadRes.rev) &&
        Objects.equals(this.uploadid, fileOsinitmultiuploadRes.uploadid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docid, name, rev, uploadid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileOsinitmultiuploadRes {\n");
    
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rev: ").append(toIndentedString(rev)).append("\n");
    sb.append("    uploadid: ").append(toIndentedString(uploadid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
