/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * FileOsbeginuploadRes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class FileOsbeginuploadRes {
  @SerializedName("authrequest")
  private List<String> authrequest = new ArrayList<String>();

  @SerializedName("docid")
  private String docid = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("rev")
  private String rev = null;

  public FileOsbeginuploadRes authrequest(List<String> authrequest) {
    this.authrequest = authrequest;
    return this;
  }

  public FileOsbeginuploadRes addAuthrequestItem(String authrequestItem) {
    this.authrequest.add(authrequestItem);
    return this;
  }

   /**
   * - authrequest[0]：请求方法  - authrequest[1]: 待上传的资源URL  - authrequest[2]及以后项：请求头，格式为“key: value”；若请求时reqmethod的值为“POST”，则为POST表单域的项，格式为“key: value”  
   * @return authrequest
  **/
  @Schema(required = true, description = "- authrequest[0]：请求方法  - authrequest[1]: 待上传的资源URL  - authrequest[2]及以后项：请求头，格式为“key: value”；若请求时reqmethod的值为“POST”，则为POST表单域的项，格式为“key: value”  ")
  public List<String> getAuthrequest() {
    return authrequest;
  }

  public void setAuthrequest(List<String> authrequest) {
    this.authrequest = authrequest;
  }

  public FileOsbeginuploadRes docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * 文件的gns路径
   * @return docid
  **/
  @Schema(required = true, description = "文件的gns路径")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }

  public FileOsbeginuploadRes name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 文件名称，UTF8编码，创建版本时返回
   * @return name
  **/
  @Schema(required = true, description = "文件名称，UTF8编码，创建版本时返回")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FileOsbeginuploadRes rev(String rev) {
    this.rev = rev;
    return this;
  }

   /**
   * 文件版本号
   * @return rev
  **/
  @Schema(required = true, description = "文件版本号")
  public String getRev() {
    return rev;
  }

  public void setRev(String rev) {
    this.rev = rev;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileOsbeginuploadRes fileOsbeginuploadRes = (FileOsbeginuploadRes) o;
    return Objects.equals(this.authrequest, fileOsbeginuploadRes.authrequest) &&
        Objects.equals(this.docid, fileOsbeginuploadRes.docid) &&
        Objects.equals(this.name, fileOsbeginuploadRes.name) &&
        Objects.equals(this.rev, fileOsbeginuploadRes.rev);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authrequest, docid, name, rev);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileOsbeginuploadRes {\n");
    
    sb.append("    authrequest: ").append(toIndentedString(authrequest)).append("\n");
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rev: ").append(toIndentedString(rev)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
