/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FileSubmitcommentReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class FileSubmitcommentReq {
  @SerializedName("docid")
  private String docid = null;

  @SerializedName("answertoid")
  private String answertoid = null;

  @SerializedName("score")
  private Long score = null;

  @SerializedName("comment")
  private String comment = null;

  public FileSubmitcommentReq docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * 文件gns路径（列举协议返回）
   * @return docid
  **/
  @Schema(required = true, description = "文件gns路径（列举协议返回）")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }

  public FileSubmitcommentReq answertoid(String answertoid) {
    this.answertoid = answertoid;
    return this;
  }

   /**
   * 被回复者id 
   * @return answertoid
  **/
  @Schema(description = "被回复者id ")
  public String getAnswertoid() {
    return answertoid;
  }

  public void setAnswertoid(String answertoid) {
    this.answertoid = answertoid;
  }

  public FileSubmitcommentReq score(Long score) {
    this.score = score;
    return this;
  }

   /**
   * 评分    评论模式mode 为 2 或 3 时（包含评分功能），需要此项    默认为 -1，表示无评分  
   * @return score
  **/
  @Schema(description = "评分    评论模式mode 为 2 或 3 时（包含评分功能），需要此项    默认为 -1，表示无评分  ")
  public Long getScore() {
    return score;
  }

  public void setScore(Long score) {
    this.score = score;
  }

  public FileSubmitcommentReq comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * 评论内容    评论模式mode 为 1 或 3 时（包含评论功能），需要此项    默认为空  
   * @return comment
  **/
  @Schema(description = "评论内容    评论模式mode 为 1 或 3 时（包含评论功能），需要此项    默认为空  ")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileSubmitcommentReq fileSubmitcommentReq = (FileSubmitcommentReq) o;
    return Objects.equals(this.docid, fileSubmitcommentReq.docid) &&
        Objects.equals(this.answertoid, fileSubmitcommentReq.answertoid) &&
        Objects.equals(this.score, fileSubmitcommentReq.score) &&
        Objects.equals(this.comment, fileSubmitcommentReq.comment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docid, answertoid, score, comment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileSubmitcommentReq {\n");
    
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("    answertoid: ").append(toIndentedString(answertoid)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
