/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FileDeletecommentReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class FileDeletecommentReq {
  @SerializedName("commentid")
  private Long commentid = null;

  @SerializedName("docid")
  private String docid = null;

  public FileDeletecommentReq commentid(Long commentid) {
    this.commentid = commentid;
    return this;
  }

   /**
   * 评论id（由获取文件评论协议返回）
   * @return commentid
  **/
  @Schema(required = true, description = "评论id（由获取文件评论协议返回）")
  public Long getCommentid() {
    return commentid;
  }

  public void setCommentid(Long commentid) {
    this.commentid = commentid;
  }

  public FileDeletecommentReq docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * 文件gns路径（列举协议返回）
   * @return docid
  **/
  @Schema(required = true, description = "文件gns路径（列举协议返回）")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileDeletecommentReq fileDeletecommentReq = (FileDeletecommentReq) o;
    return Objects.equals(this.commentid, fileDeletecommentReq.commentid) &&
        Objects.equals(this.docid, fileDeletecommentReq.docid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commentid, docid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileDeletecommentReq {\n");
    
    sb.append("    commentid: ").append(toIndentedString(commentid)).append("\n");
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
