/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * LinkOsenduploadReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class LinkOsenduploadReq {
  @SerializedName("crc32")
  private String crc32 = null;

  @SerializedName("docid")
  private String docid = null;

  @SerializedName("md5")
  private String md5 = null;

  @SerializedName("slice_md5")
  private String sliceMd5 = null;

  @SerializedName("rev")
  private String rev = null;

  @SerializedName("link")
  private String link = null;

  public LinkOsenduploadReq crc32(String crc32) {
    this.crc32 = crc32;
    return this;
  }

   /**
   * 文件的CRC32校验码
   * @return crc32
  **/
  @Schema(description = "文件的CRC32校验码")
  public String getCrc32() {
    return crc32;
  }

  public void setCrc32(String crc32) {
    this.crc32 = crc32;
  }

  public LinkOsenduploadReq docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * 文件gns路径（创建协议返回）
   * @return docid
  **/
  @Schema(required = true, description = "文件gns路径（创建协议返回）")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }

  public LinkOsenduploadReq md5(String md5) {
    this.md5 = md5;
    return this;
  }

   /**
   * 文件MD5值
   * @return md5
  **/
  @Schema(description = "文件MD5值")
  public String getMd5() {
    return md5;
  }

  public void setMd5(String md5) {
    this.md5 = md5;
  }

  public LinkOsenduploadReq sliceMd5(String sliceMd5) {
    this.sliceMd5 = sliceMd5;
    return this;
  }

   /**
   * 文件的slice_md5
   * @return sliceMd5
  **/
  @Schema(description = "文件的slice_md5")
  public String getSliceMd5() {
    return sliceMd5;
  }

  public void setSliceMd5(String sliceMd5) {
    this.sliceMd5 = sliceMd5;
  }

  public LinkOsenduploadReq rev(String rev) {
    this.rev = rev;
    return this;
  }

   /**
   * 文件版本号
   * @return rev
  **/
  @Schema(required = true, description = "文件版本号")
  public String getRev() {
    return rev;
  }

  public void setRev(String rev) {
    this.rev = rev;
  }

  public LinkOsenduploadReq link(String link) {
    this.link = link;
    return this;
  }

   /**
   * 外链ID
   * @return link
  **/
  @Schema(required = true, description = "外链ID")
  public String getLink() {
    return link;
  }

  public void setLink(String link) {
    this.link = link;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkOsenduploadReq linkOsenduploadReq = (LinkOsenduploadReq) o;
    return Objects.equals(this.crc32, linkOsenduploadReq.crc32) &&
        Objects.equals(this.docid, linkOsenduploadReq.docid) &&
        Objects.equals(this.md5, linkOsenduploadReq.md5) &&
        Objects.equals(this.sliceMd5, linkOsenduploadReq.sliceMd5) &&
        Objects.equals(this.rev, linkOsenduploadReq.rev) &&
        Objects.equals(this.link, linkOsenduploadReq.link);
  }

  @Override
  public int hashCode() {
    return Objects.hash(crc32, docid, md5, sliceMd5, rev, link);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkOsenduploadReq {\n");
    
    sb.append("    crc32: ").append(toIndentedString(crc32)).append("\n");
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("    md5: ").append(toIndentedString(md5)).append("\n");
    sb.append("    sliceMd5: ").append(toIndentedString(sliceMd5)).append("\n");
    sb.append("    rev: ").append(toIndentedString(rev)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
