/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * LinkGetlinkedResItem
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class LinkGetlinkedResItem {
  @SerializedName("docid")
  private String docid = null;

  @SerializedName("namepath")
  private String namepath = null;

  @SerializedName("size")
  private Long size = null;

  @SerializedName("modified")
  private Long modified = null;

  public LinkGetlinkedResItem docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * 外链访问的文件gns路径
   * @return docid
  **/
  @Schema(required = true, description = "外链访问的文件gns路径")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }

  public LinkGetlinkedResItem namepath(String namepath) {
    this.namepath = namepath;
    return this;
  }

   /**
   * 外链访问的文件name路径
   * @return namepath
  **/
  @Schema(required = true, description = "外链访问的文件name路径")
  public String getNamepath() {
    return namepath;
  }

  public void setNamepath(String namepath) {
    this.namepath = namepath;
  }

  public LinkGetlinkedResItem size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * 外链访问的文件大小
   * @return size
  **/
  @Schema(required = true, description = "外链访问的文件大小")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public LinkGetlinkedResItem modified(Long modified) {
    this.modified = modified;
    return this;
  }

   /**
   * 外链访问的文件最后修改时间
   * @return modified
  **/
  @Schema(required = true, description = "外链访问的文件最后修改时间")
  public Long getModified() {
    return modified;
  }

  public void setModified(Long modified) {
    this.modified = modified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkGetlinkedResItem linkGetlinkedResItem = (LinkGetlinkedResItem) o;
    return Objects.equals(this.docid, linkGetlinkedResItem.docid) &&
        Objects.equals(this.namepath, linkGetlinkedResItem.namepath) &&
        Objects.equals(this.size, linkGetlinkedResItem.size) &&
        Objects.equals(this.modified, linkGetlinkedResItem.modified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docid, namepath, size, modified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkGetlinkedResItem {\n");
    
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("    namepath: ").append(toIndentedString(namepath)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
