/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * LinkCopyReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class LinkCopyReq {
  @SerializedName("destparent")
  private String destparent = null;

  @SerializedName("docid")
  private String docid = null;

  @SerializedName("link")
  private String link = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("ondup")
  private Long ondup = null;

  public LinkCopyReq destparent(String destparent) {
    this.destparent = destparent;
    return this;
  }

   /**
   * 目标父对象的gns路径，无法复制到原位置的子目录下
   * @return destparent
  **/
  @Schema(required = true, description = "目标父对象的gns路径，无法复制到原位置的子目录下")
  public String getDestparent() {
    return destparent;
  }

  public void setDestparent(String destparent) {
    this.destparent = destparent;
  }

  public LinkCopyReq docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * gns路径，通过文件夹外链复制其中的子对象时，需要该参数，默认为空
   * @return docid
  **/
  @Schema(description = "gns路径，通过文件夹外链复制其中的子对象时，需要该参数，默认为空")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }

  public LinkCopyReq link(String link) {
    this.link = link;
    return this;
  }

   /**
   * 外链唯一标识，如FC5E038D38A57032085441E7FE7010B0
   * @return link
  **/
  @Schema(required = true, description = "外链唯一标识，如FC5E038D38A57032085441E7FE7010B0")
  public String getLink() {
    return link;
  }

  public void setLink(String link) {
    this.link = link;
  }

  public LinkCopyReq password(String password) {
    this.password = password;
    return this;
  }

   /**
   * 密码
   * @return password
  **/
  @Schema(required = true, description = "密码")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public LinkCopyReq ondup(Long ondup) {
    this.ondup = ondup;
    return this;
  }

   /**
   * 1:检查是否重命名，重名则抛异常  2:默认值，如果重名冲突，自动重名  3:如果重名冲突，自动覆盖  
   * @return ondup
  **/
  @Schema(description = "1:检查是否重命名，重名则抛异常  2:默认值，如果重名冲突，自动重名  3:如果重名冲突，自动覆盖  ")
  public Long getOndup() {
    return ondup;
  }

  public void setOndup(Long ondup) {
    this.ondup = ondup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkCopyReq linkCopyReq = (LinkCopyReq) o;
    return Objects.equals(this.destparent, linkCopyReq.destparent) &&
        Objects.equals(this.docid, linkCopyReq.docid) &&
        Objects.equals(this.link, linkCopyReq.link) &&
        Objects.equals(this.password, linkCopyReq.password) &&
        Objects.equals(this.ondup, linkCopyReq.ondup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destparent, docid, link, password, ondup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkCopyReq {\n");
    
    sb.append("    destparent: ").append(toIndentedString(destparent)).append("\n");
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    ondup: ").append(toIndentedString(ondup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
