/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * LinkListdirResDir
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class LinkListdirResDir {
  @SerializedName("docid")
  private String docid = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("rev")
  private String rev = null;

  @SerializedName("size")
  private Long size = null;

  @SerializedName("modified")
  private Long modified = null;

  public LinkListdirResDir docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * 目录中文件/目录的gns路径
   * @return docid
  **/
  @Schema(required = true, description = "目录中文件/目录的gns路径")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }

  public LinkListdirResDir name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 目录中文件/目录的名称，UTF8编码
   * @return name
  **/
  @Schema(required = true, description = "目录中文件/目录的名称，UTF8编码")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LinkListdirResDir rev(String rev) {
    this.rev = rev;
    return this;
  }

   /**
   * 目录中文件版本号或目录数据变化标识
   * @return rev
  **/
  @Schema(required = true, description = "目录中文件版本号或目录数据变化标识")
  public String getRev() {
    return rev;
  }

  public void setRev(String rev) {
    this.rev = rev;
  }

  public LinkListdirResDir size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * 目录中文件的大小，目录大小为-1
   * @return size
  **/
  @Schema(required = true, description = "目录中文件的大小，目录大小为-1")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public LinkListdirResDir modified(Long modified) {
    this.modified = modified;
    return this;
  }

   /**
   * 目录修改时间/文件上传时间，UTC时间，此为文件上传到服务器时间
   * @return modified
  **/
  @Schema(required = true, description = "目录修改时间/文件上传时间，UTC时间，此为文件上传到服务器时间")
  public Long getModified() {
    return modified;
  }

  public void setModified(Long modified) {
    this.modified = modified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkListdirResDir linkListdirResDir = (LinkListdirResDir) o;
    return Objects.equals(this.docid, linkListdirResDir.docid) &&
        Objects.equals(this.name, linkListdirResDir.name) &&
        Objects.equals(this.rev, linkListdirResDir.rev) &&
        Objects.equals(this.size, linkListdirResDir.size) &&
        Objects.equals(this.modified, linkListdirResDir.modified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docid, name, rev, size, modified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkListdirResDir {\n");
    
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rev: ").append(toIndentedString(rev)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
