/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Perm1GetexternallinktemplateRes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class Perm1GetexternallinktemplateRes {
  @SerializedName("limitexpiredays")
  private Boolean limitexpiredays = null;

  @SerializedName("allowexpiredays")
  private Long allowexpiredays = null;

  @SerializedName("allowperm")
  private Long allowperm = null;

  @SerializedName("defaultperm")
  private Long defaultperm = null;

  @SerializedName("limitaccesstimes")
  private Boolean limitaccesstimes = null;

  @SerializedName("allowaccesstimes")
  private Long allowaccesstimes = null;

  @SerializedName("accesspassword")
  private Boolean accesspassword = null;

  public Perm1GetexternallinktemplateRes limitexpiredays(Boolean limitexpiredays) {
    this.limitexpiredays = limitexpiredays;
    return this;
  }

   /**
   * 是否限制外链有效期
   * @return limitexpiredays
  **/
  @Schema(required = true, description = "是否限制外链有效期")
  public Boolean isLimitexpiredays() {
    return limitexpiredays;
  }

  public void setLimitexpiredays(Boolean limitexpiredays) {
    this.limitexpiredays = limitexpiredays;
  }

  public Perm1GetexternallinktemplateRes allowexpiredays(Long allowexpiredays) {
    this.allowexpiredays = allowexpiredays;
    return this;
  }

   /**
   * limitexpireday&#x3D;fasle  表示默认有效期  limitexpireday&#x3D;true  表示最大有效期
   * @return allowexpiredays
  **/
  @Schema(required = true, description = "limitexpireday=fasle  表示默认有效期  limitexpireday=true  表示最大有效期")
  public Long getAllowexpiredays() {
    return allowexpiredays;
  }

  public void setAllowexpiredays(Long allowexpiredays) {
    this.allowexpiredays = allowexpiredays;
  }

  public Perm1GetexternallinktemplateRes allowperm(Long allowperm) {
    this.allowperm = allowperm;
    return this;
  }

   /**
   * 可设定的权限
   * @return allowperm
  **/
  @Schema(required = true, description = "可设定的权限")
  public Long getAllowperm() {
    return allowperm;
  }

  public void setAllowperm(Long allowperm) {
    this.allowperm = allowperm;
  }

  public Perm1GetexternallinktemplateRes defaultperm(Long defaultperm) {
    this.defaultperm = defaultperm;
    return this;
  }

   /**
   * 默认权限
   * @return defaultperm
  **/
  @Schema(required = true, description = "默认权限")
  public Long getDefaultperm() {
    return defaultperm;
  }

  public void setDefaultperm(Long defaultperm) {
    this.defaultperm = defaultperm;
  }

  public Perm1GetexternallinktemplateRes limitaccesstimes(Boolean limitaccesstimes) {
    this.limitaccesstimes = limitaccesstimes;
    return this;
  }

   /**
   * 是否限制打开次数
   * @return limitaccesstimes
  **/
  @Schema(required = true, description = "是否限制打开次数")
  public Boolean isLimitaccesstimes() {
    return limitaccesstimes;
  }

  public void setLimitaccesstimes(Boolean limitaccesstimes) {
    this.limitaccesstimes = limitaccesstimes;
  }

  public Perm1GetexternallinktemplateRes allowaccesstimes(Long allowaccesstimes) {
    this.allowaccesstimes = allowaccesstimes;
    return this;
  }

   /**
   * limitaccesstimes&#x3D;false  表示默认打开次数  limitaccesstimes&#x3D;true  表示最大打开次数
   * @return allowaccesstimes
  **/
  @Schema(required = true, description = "limitaccesstimes=false  表示默认打开次数  limitaccesstimes=true  表示最大打开次数")
  public Long getAllowaccesstimes() {
    return allowaccesstimes;
  }

  public void setAllowaccesstimes(Long allowaccesstimes) {
    this.allowaccesstimes = allowaccesstimes;
  }

  public Perm1GetexternallinktemplateRes accesspassword(Boolean accesspassword) {
    this.accesspassword = accesspassword;
    return this;
  }

   /**
   * 是否强制使用访问密码
   * @return accesspassword
  **/
  @Schema(required = true, description = "是否强制使用访问密码")
  public Boolean isAccesspassword() {
    return accesspassword;
  }

  public void setAccesspassword(Boolean accesspassword) {
    this.accesspassword = accesspassword;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Perm1GetexternallinktemplateRes perm1GetexternallinktemplateRes = (Perm1GetexternallinktemplateRes) o;
    return Objects.equals(this.limitexpiredays, perm1GetexternallinktemplateRes.limitexpiredays) &&
        Objects.equals(this.allowexpiredays, perm1GetexternallinktemplateRes.allowexpiredays) &&
        Objects.equals(this.allowperm, perm1GetexternallinktemplateRes.allowperm) &&
        Objects.equals(this.defaultperm, perm1GetexternallinktemplateRes.defaultperm) &&
        Objects.equals(this.limitaccesstimes, perm1GetexternallinktemplateRes.limitaccesstimes) &&
        Objects.equals(this.allowaccesstimes, perm1GetexternallinktemplateRes.allowaccesstimes) &&
        Objects.equals(this.accesspassword, perm1GetexternallinktemplateRes.accesspassword);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limitexpiredays, allowexpiredays, allowperm, defaultperm, limitaccesstimes, allowaccesstimes, accesspassword);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Perm1GetexternallinktemplateRes {\n");
    
    sb.append("    limitexpiredays: ").append(toIndentedString(limitexpiredays)).append("\n");
    sb.append("    allowexpiredays: ").append(toIndentedString(allowexpiredays)).append("\n");
    sb.append("    allowperm: ").append(toIndentedString(allowperm)).append("\n");
    sb.append("    defaultperm: ").append(toIndentedString(defaultperm)).append("\n");
    sb.append("    limitaccesstimes: ").append(toIndentedString(limitaccesstimes)).append("\n");
    sb.append("    allowaccesstimes: ").append(toIndentedString(allowaccesstimes)).append("\n");
    sb.append("    accesspassword: ").append(toIndentedString(accesspassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
