/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openDocAPI.client.model.Perm1ListResOwnerresult;
import io.openDocAPI.client.model.Perm1ListResPermresult;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Perm1ListRes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class Perm1ListRes {
  @SerializedName("permresults")
  private List<Perm1ListResPermresult> permresults = new ArrayList<Perm1ListResPermresult>();

  @SerializedName("ownerresults")
  private List<Perm1ListResOwnerresult> ownerresults = new ArrayList<Perm1ListResOwnerresult>();

  public Perm1ListRes permresults(List<Perm1ListResPermresult> permresults) {
    this.permresults = permresults;
    return this;
  }

  public Perm1ListRes addPermresultsItem(Perm1ListResPermresult permresultsItem) {
    this.permresults.add(permresultsItem);
    return this;
  }

   /**
   * 最终权限信息
   * @return permresults
  **/
  @Schema(required = true, description = "最终权限信息")
  public List<Perm1ListResPermresult> getPermresults() {
    return permresults;
  }

  public void setPermresults(List<Perm1ListResPermresult> permresults) {
    this.permresults = permresults;
  }

  public Perm1ListRes ownerresults(List<Perm1ListResOwnerresult> ownerresults) {
    this.ownerresults = ownerresults;
    return this;
  }

  public Perm1ListRes addOwnerresultsItem(Perm1ListResOwnerresult ownerresultsItem) {
    this.ownerresults.add(ownerresultsItem);
    return this;
  }

   /**
   * 最终所有者信息
   * @return ownerresults
  **/
  @Schema(required = true, description = "最终所有者信息")
  public List<Perm1ListResOwnerresult> getOwnerresults() {
    return ownerresults;
  }

  public void setOwnerresults(List<Perm1ListResOwnerresult> ownerresults) {
    this.ownerresults = ownerresults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Perm1ListRes perm1ListRes = (Perm1ListRes) o;
    return Objects.equals(this.permresults, perm1ListRes.permresults) &&
        Objects.equals(this.ownerresults, perm1ListRes.ownerresults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(permresults, ownerresults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Perm1ListRes {\n");
    
    sb.append("    permresults: ").append(toIndentedString(permresults)).append("\n");
    sb.append("    ownerresults: ").append(toIndentedString(ownerresults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
