/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * QuarantineListreversionRes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class QuarantineListreversionRes {
  @SerializedName("modified")
  private Long modified = null;

  @SerializedName("modifier")
  private String modifier = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("reason")
  private String reason = null;

  @SerializedName("rev")
  private String rev = null;

  public QuarantineListreversionRes modified(Long modified) {
    this.modified = modified;
    return this;
  }

   /**
   * 版本修改时间
   * @return modified
  **/
  @Schema(required = true, description = "版本修改时间")
  public Long getModified() {
    return modified;
  }

  public void setModified(Long modified) {
    this.modified = modified;
  }

  public QuarantineListreversionRes modifier(String modifier) {
    this.modifier = modifier;
    return this;
  }

   /**
   * 版本修改者名称
   * @return modifier
  **/
  @Schema(required = true, description = "版本修改者名称")
  public String getModifier() {
    return modifier;
  }

  public void setModifier(String modifier) {
    this.modifier = modifier;
  }

  public QuarantineListreversionRes name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 版本名称
   * @return name
  **/
  @Schema(required = true, description = "版本名称")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public QuarantineListreversionRes reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * 版本隔离原因
   * @return reason
  **/
  @Schema(required = true, description = "版本隔离原因")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public QuarantineListreversionRes rev(String rev) {
    this.rev = rev;
    return this;
  }

   /**
   * 版本id
   * @return rev
  **/
  @Schema(required = true, description = "版本id")
  public String getRev() {
    return rev;
  }

  public void setRev(String rev) {
    this.rev = rev;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuarantineListreversionRes quarantineListreversionRes = (QuarantineListreversionRes) o;
    return Objects.equals(this.modified, quarantineListreversionRes.modified) &&
        Objects.equals(this.modifier, quarantineListreversionRes.modifier) &&
        Objects.equals(this.name, quarantineListreversionRes.name) &&
        Objects.equals(this.reason, quarantineListreversionRes.reason) &&
        Objects.equals(this.rev, quarantineListreversionRes.rev);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modified, modifier, name, reason, rev);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuarantineListreversionRes {\n");
    
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    modifier: ").append(toIndentedString(modifier)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    rev: ").append(toIndentedString(rev)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
