/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * QuarantinePreviewReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class QuarantinePreviewReq {
  @SerializedName("docid")
  private String docid = null;

  @SerializedName("rev")
  private String rev = null;

  @SerializedName("reqhost")
  private String reqhost = null;

  @SerializedName("usehttps")
  private Boolean usehttps = null;

  public QuarantinePreviewReq docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * 文件docid
   * @return docid
  **/
  @Schema(required = true, description = "文件docid")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }

  public QuarantinePreviewReq rev(String rev) {
    this.rev = rev;
    return this;
  }

   /**
   * 预览版本ID （不可为空）
   * @return rev
  **/
  @Schema(required = true, description = "预览版本ID （不可为空）")
  public String getRev() {
    return rev;
  }

  public void setRev(String rev) {
    this.rev = rev;
  }

  public QuarantinePreviewReq reqhost(String reqhost) {
    this.reqhost = reqhost;
    return this;
  }

   /**
   * 从存储服务器下载数据时的请求地址从存储服务器下载数据时的请求地址
   * @return reqhost
  **/
  @Schema(description = "从存储服务器下载数据时的请求地址从存储服务器下载数据时的请求地址")
  public String getReqhost() {
    return reqhost;
  }

  public void setReqhost(String reqhost) {
    this.reqhost = reqhost;
  }

  public QuarantinePreviewReq usehttps(Boolean usehttps) {
    this.usehttps = usehttps;
    return this;
  }

   /**
   * 是否使用https下载数据，默认为true
   * @return usehttps
  **/
  @Schema(description = "是否使用https下载数据，默认为true")
  public Boolean isUsehttps() {
    return usehttps;
  }

  public void setUsehttps(Boolean usehttps) {
    this.usehttps = usehttps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuarantinePreviewReq quarantinePreviewReq = (QuarantinePreviewReq) o;
    return Objects.equals(this.docid, quarantinePreviewReq.docid) &&
        Objects.equals(this.rev, quarantinePreviewReq.rev) &&
        Objects.equals(this.reqhost, quarantinePreviewReq.reqhost) &&
        Objects.equals(this.usehttps, quarantinePreviewReq.usehttps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docid, rev, reqhost, usehttps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuarantinePreviewReq {\n");
    
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("    rev: ").append(toIndentedString(rev)).append("\n");
    sb.append("    reqhost: ").append(toIndentedString(reqhost)).append("\n");
    sb.append("    usehttps: ").append(toIndentedString(usehttps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
