/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RecycleListResDirs
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class RecycleListResDirs {
  @SerializedName("docid")
  private String docid = null;

  @SerializedName("editor")
  private String editor = null;

  @SerializedName("modified")
  private Long modified = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("path")
  private String path = null;

  @SerializedName("size")
  private Long size = null;

  public RecycleListResDirs docid(String docid) {
    this.docid = docid;
    return this;
  }

   /**
   * 回收站中文件/目录的gns路径
   * @return docid
  **/
  @Schema(required = true, description = "回收站中文件/目录的gns路径")
  public String getDocid() {
    return docid;
  }

  public void setDocid(String docid) {
    this.docid = docid;
  }

  public RecycleListResDirs editor(String editor) {
    this.editor = editor;
    return this;
  }

   /**
   * 回收站中文件/目录删除者的名称
   * @return editor
  **/
  @Schema(required = true, description = "回收站中文件/目录删除者的名称")
  public String getEditor() {
    return editor;
  }

  public void setEditor(String editor) {
    this.editor = editor;
  }

  public RecycleListResDirs modified(Long modified) {
    this.modified = modified;
    return this;
  }

   /**
   * 回收站中文件/目录的删除时间
   * @return modified
  **/
  @Schema(required = true, description = "回收站中文件/目录的删除时间")
  public Long getModified() {
    return modified;
  }

  public void setModified(Long modified) {
    this.modified = modified;
  }

  public RecycleListResDirs name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 回收站中文件/目录的名称，UTF8编码
   * @return name
  **/
  @Schema(required = true, description = "回收站中文件/目录的名称，UTF8编码")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RecycleListResDirs path(String path) {
    this.path = path;
    return this;
  }

   /**
   * 回收站中文件/目录的原路径，UTF8编码
   * @return path
  **/
  @Schema(required = true, description = "回收站中文件/目录的原路径，UTF8编码")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public RecycleListResDirs size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * 回收站中文件的大小，目录大小为-1
   * @return size
  **/
  @Schema(required = true, description = "回收站中文件的大小，目录大小为-1")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecycleListResDirs recycleListResDirs = (RecycleListResDirs) o;
    return Objects.equals(this.docid, recycleListResDirs.docid) &&
        Objects.equals(this.editor, recycleListResDirs.editor) &&
        Objects.equals(this.modified, recycleListResDirs.modified) &&
        Objects.equals(this.name, recycleListResDirs.name) &&
        Objects.equals(this.path, recycleListResDirs.path) &&
        Objects.equals(this.size, recycleListResDirs.size);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docid, editor, modified, name, path, size);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecycleListResDirs {\n");
    
    sb.append("    docid: ").append(toIndentedString(docid)).append("\n");
    sb.append("    editor: ").append(toIndentedString(editor)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
