/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SearchCustomattributeResItem
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class SearchCustomattributeResItem {
  @SerializedName("name")
  private String name = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("type")
  private Long type = null;

  public SearchCustomattributeResItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 属性名称
   * @return name
  **/
  @Schema(required = true, description = "属性名称")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SearchCustomattributeResItem id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * 属性唯一ID
   * @return id
  **/
  @Schema(required = true, description = "属性唯一ID")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SearchCustomattributeResItem type(Long type) {
    this.type = type;
    return this;
  }

   /**
   * 属性类型  0：层级  1：枚举  2：数字  3：文本  4：时间 （时间戳）  
   * @return type
  **/
  @Schema(required = true, description = "属性类型  0：层级  1：枚举  2：数字  3：文本  4：时间 （时间戳）  ")
  public Long getType() {
    return type;
  }

  public void setType(Long type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchCustomattributeResItem searchCustomattributeResItem = (SearchCustomattributeResItem) o;
    return Objects.equals(this.name, searchCustomattributeResItem.name) &&
        Objects.equals(this.id, searchCustomattributeResItem.id) &&
        Objects.equals(this.type, searchCustomattributeResItem.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, id, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchCustomattributeResItem {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
