/*
 * 6.0-OpenDoc_API-文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * OpenAPI spec version: 6.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openDocAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openDocAPI.client.model.SearchSearchResHighlighting;
import io.openDocAPI.client.model.SearchSearchResResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SearchSearchRes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-28T09:01:49.177Z[Etc/UTC]")
public class SearchSearchRes {
  @SerializedName("response")
  private SearchSearchResResponse response = null;

  @SerializedName("highlighting")
  private SearchSearchResHighlighting highlighting = null;

  public SearchSearchRes response(SearchSearchResResponse response) {
    this.response = response;
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  @Schema(required = true, description = "")
  public SearchSearchResResponse getResponse() {
    return response;
  }

  public void setResponse(SearchSearchResResponse response) {
    this.response = response;
  }

  public SearchSearchRes highlighting(SearchSearchResHighlighting highlighting) {
    this.highlighting = highlighting;
    return this;
  }

   /**
   * Get highlighting
   * @return highlighting
  **/
  @Schema(description = "")
  public SearchSearchResHighlighting getHighlighting() {
    return highlighting;
  }

  public void setHighlighting(SearchSearchResHighlighting highlighting) {
    this.highlighting = highlighting;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchSearchRes searchSearchRes = (SearchSearchRes) o;
    return Objects.equals(this.response, searchSearchRes.response) &&
        Objects.equals(this.highlighting, searchSearchRes.highlighting);
  }

  @Override
  public int hashCode() {
    return Objects.hash(response, highlighting);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchSearchRes {\n");
    
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    highlighting: ").append(toIndentedString(highlighting)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
